name: Build SkyblockTweaks

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build-gradle-project:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-java@v4.0.0
        with:
          distribution: zulu
          java-version: 17

      - name: Checkout repo
        uses: actions/checkout@v4.1.1

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Setup Gradle and build jar
        uses: gradle/gradle-build-action@v2.11.1
        with:
          arguments: build

      - name: Upload SkyblockTweaks jar
        uses: actions/upload-artifact@v4.0.0
        with:
          name: SkyblockTweaks-Nightly
          path: build/libs/*.jar
